### ISSUE TITLE
error: Can not locate config makefile for product "twrp_NX699J".

### ISSUE THREAD

**Issue by qbbyybyby** [azwhikaru/Action-TWRP-Builder#54]
I got this error when building twrp for my android 12 device
device tree: https://github.com/twrpdtgen/android_device_nubia_NX669J
MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
Build Target: Boot
Device tree modified for twrp aosp: https://github.com/qbbyybyby/android_device_nubia_NX669J
Tried both device tree url but still got same error

**Comment by lopestom** [comment]
> I got this error when building twrp for my android 12 device device tree: https://github.com/twrpdtgen/android_device_nubia_NX669J MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git Build Target: Boot Device tree modified for twrp aosp: https://github.com/qbbyybyby/android_device_nubia_NX669J Tried both device tree url but still got same error

Because your DT is wrong!!
omni_NX669J.mk
PRODUCT_NAME := twrp_NX669J

If you using platform_manifest_twrp_aosp.git so ALL files need ` twrp_`
Therefore change omni_NX669J.mk to twrp_NX669J.mk acordding your own reference https://github.com/qbbyybyby/twrp_device_nubia_NX669J/blob/f575be5c72fff82af100807b2ed6ab2d8e465329/AndroidProducts.mk#L9
